Bubble Sort Algorithm
Samitti/bubble_sort pull request #1
Opened 2020-04-20 10:48 UTC by Samitti

We did two assignments from Odin projects on the bubble sort algorithm.

2020-04-20 18:19 UTC, pelzolga123 requested changes
The project requires changes.

2020-04-20 18:19 UTC, pelzolga123 commented
## Hi Team! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your did a great job!
Just a few minor changes left:
* [ ]  README file should have a short description on how to run your project.
* [ ] There should be no debugging instructions in committed code (as discussed [here](https://questions.microverse.org/t/debugging-instructions-code/346)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/section/debugging_requirement.png) from Pathwright)
* [ ] Rename `sort_bubble` method to `bubble_sort_by`, so it's easier to understand what that method does.

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-04-21 07:58 UTC, NiiazalyDzhumaliev commented
Thanks for the review. We changed the name of bubble_sort to bubble_sort_by, add a description to the README file and in the future won't use debugging instructions in commits. Please, kindly review our project.

2020-04-21 10:46 UTC, stratospherique approved these changes
### Great work implementing the suggested changes :clap: Congrats, the project is approved :heavy_check_mark: You may merge :+1: :+1: :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**
#### PS: Check the code comments below, they indicate a minor issue in your code that you should fix before you merge.

2020-04-21 10:46 UTC, stratospherique commented on bubble_sort.rb
> +puts bubble_sort([4, 3, 78, 2, 0, 2])
- There should be no debugging instructions in committed code.

2020-04-21 10:46 UTC, stratospherique commented on bubble_sort.rb
> +puts sort_bubble(%w[hello hi hey]) { |right, left| right.length - left.length }
- There should be no debugging instructions in committed code.

2020-04-21 12:09 UTC, merged